### ISSUE TITLE
Handle both Alfresco and ssh based on configuration

### ISSUE THREAD

**Issue by bandrzejczak** [bms-devs/FileSynchronizer#6]
In this moment to swich between Alfresco and ssh you need to change class in the source code and recompile the application. I'd like to have some way of determining what `FileSynchronizer` implementation should be instantiated. One way I can think of is to look for `workspace://` prefix inside destinationRoot configuration field, which would mean Alfresco. I'm open to other options.

**Comment by wojda** [comment]
Next idea: Prepare two config files, one for Alfresco, one for ssh. If **alfresco.config.json** is available - FileSynchronizer will read it and send file to Alfresco. The same for **ssh.config.json**. Moreover, we can handle situation where both file are provided. @bandrzejczak WDYT?

**Comment by bandrzejczak** [comment]
@wojda I don't think it's such a good idea to differentiate configs on file names. I'd even prefer to put an explicit field in configuration json like *remoteHostType*. Storing data in file names sounds like a bad idea.
Handling different config files is a good idea, but I thing it should be handled in a different way, hence I created issue #14.
